In [2]:
import numpy as np

In [7]:
# creating an array and defining its data type
num = np.arange(0,21,2, dtype=np.int16)

In [4]:
num

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20], dtype=int16)

In [8]:
num

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20], dtype=int16)

In [5]:
type(num)

numpy.ndarray

In [6]:
# adding all the elements of an array
total = 0
for i in range(len(num)):
    total = total + num[i]
print(total)

110


In [ ]:
sum(num)

110

In [ ]:
num1 = np.arange(0,21,2, dtype=np.int8)

In [ ]:
num1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20], dtype=int8)

In [ ]:
# choosing the elements of an ayyar to which to show
j = []
for i in range(0,len(num1)):
    if (num1[i] > 8):
        j.append(num1[i])

In [ ]:
j

[10, 12, 14, 16, 18, 20]

In [ ]:
sum(j)

90

In [ ]:
np.array(j)

array([10, 12, 14, 16, 18, 20], dtype=int8)

In [ ]:
# for checking time taken to exicute it in numpy and python 

In [ ]:
import numpy as np

In [ ]:
np_array = np.arange(1000)
p_list   = list(range(1000))

%timeit for _ in range(10): np_array2 = np_array * 2

16.6 µs ± 706 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit for _ in range(10): p_list2 = [x * 2 for x in p_list]

667 µs ± 59.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
import numpy as np

In [ ]:
number = np.int8(127)
print(number, type(number))

127 <class 'numpy.int8'>


In [ ]:
# as it exides the range if that intiger it will give the value in the negative 

number = np.int8(200)
print(number, type(number))

-56 <class 'numpy.int8'>


In [ ]:
# Unsinged int8
number1 = np.uint8(540)
print(number1,type(number1))

28 <class 'numpy.uint8'>


In [ ]:
number = np.array([1,2,3,4])
print(number, type(number))

[1 2 3 4] <class 'numpy.ndarray'>


In [ ]:
print(number.dtype)

int64


In [ ]:
# pre defining of data type
num1 = np.array([1,2,3,4], dtype=np.float64)
print(num1, type(num1), num1.dtype)

[1. 2. 3. 4.] <class 'numpy.ndarray'> float64


In [ ]:
# mixed array
kanishk = np.array([1,2,3.0,4,'kanishk'])
print(kanishk, type(kanishk), kanishk.dtype)

['1' '2' '3.0' '4' 'kanishk'] <class 'numpy.ndarray'> <U32


In [ ]:
type(kanishk)

numpy.ndarray

In [ ]:
kanishk.dtype

dtype('<U32')

In [ ]:
# giving it a float value
kan = np.arange(1,20,0.5, dtype = np.float16)
print(kan, type(kan), kan.dtype)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5] <class 'numpy.ndarray'> float16


In [ ]:
# array formed in matrix
mylist = [
            [5,4,8],
            [6,4,9],
            [6,5,2]
        ]

In [ ]:
get = np.array(mylist,dtype=np.int8)

In [ ]:
print(get, type(get), get.dtype)

[[5 4 8]
 [6 4 9]
 [6 5 2]] <class 'numpy.ndarray'> int8


In [ ]:
# for an array having all the eliment as 1
my_one_array = np.ones(shape = (1,5) , dtype=np.float16)
print(my_one_array,type(my_one_array),my_one_array.dtype)

[[1. 1. 1. 1. 1.]] <class 'numpy.ndarray'> float16


In [ ]:
# if we want all the eliments as zero then just put zero at the place of ones
my_one_array = np.zeros(shape = (3,3) , dtype=np.float16)
print(my_one_array,type(my_one_array),my_one_array.dtype)
# we can also change the shape of the array by defining the shape 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'> float16


In [ ]:
# making an array in np array
my_array = np.full(shape = (5,2), fill_value = 10, dtype = np.int16)
print(my_array, type(my_array), my_array.dtype)

[[10 10]
 [10 10]
 [10 10]
 [10 10]
 [10 10]] <class 'numpy.ndarray'> int16


In [ ]:
# changing the shapy of an array
my_array = my_array.reshape(2,5)
my_array

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]], dtype=int16)

In [ ]:
# we can also fill the space by some value
my_one_array = np.full(shape = (3,5),fill_value = 20, dtype=np.float16)
print(my_one_array,type(my_one_array),my_one_array.dtype)

[[20. 20. 20. 20. 20.]
 [20. 20. 20. 20. 20.]
 [20. 20. 20. 20. 20.]] <class 'numpy.ndarray'> float16


In [ ]:
# telling the shape of an array
array = np.arange(0,10)
print("Your array is: ", array)
print("shape of array is: " , array.shape  , "i.e. it have only 10 columns")

Your array is:  [0 1 2 3 4 5 6 7 8 9]
shape of array is:  (10,) i.e. it have only 10 columns


In [ ]:
# we can reshape a array by aplying this function 
array = array.reshape(10,1)

In [ ]:
array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
# we can change the data type by using astype

array1 = np.array([1,2,3,4], dtype = np.int16)
print(array, array.dtype)

print("\nnow we r changing the data type of that array\n")

array1 = array1.astype(np.float16)
print(array1 , array1.dtype)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] int32

now we r changing the data type of that array

[1. 2. 3. 4.] float16


In [ ]:
#changing the element in an array
print(get)
print("\n the shape of the array is: ",get.shape)
get[0][2] = 10
print(get)

[[5 4 8]
 [6 4 9]
 [6 5 2]]

 the shape of the array is:  (3, 3)
[[ 5  4 10]
 [ 6  4  9]
 [ 6  5  2]]


# OPERATIONS 

In [ ]:
num = np.arange(0,21,2, dtype = np.int16)

In [ ]:
num

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20], dtype=int16)

In [ ]:
# function for adding all the elements in an array
def total(array):
    total = 0
    for i in array:
        total += i
    return(total)

In [ ]:
total(num)

110

In [ ]:
print(num.__doc__) # it takes a dimentional array and returns a sum of that array

None


In [ ]:
# we can also use inbuilt function sum of python
sum(num)

110

In [ ]:
#for numpy array
num.sum()

110

In [ ]:
# lets see the time taken 
# in python
%timeit sum(num)

3.73 µs ± 130 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
# in numpy
%timeit num.sum()

1.85 µs ± 38.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
# finding mean and standard deviation 
print("mean is: ", num.mean())
print("sd is: ", num.std())

mean is:  10.0
sd is:  6.324555320336759


In [ ]:
# finding the variance
num.var()

40.0

# MIN and MAX

In [ ]:
num.min()

0

In [ ]:
num.max()

20

In [ ]:
# axis 0 is for column and axis 1 is for rows

In [ ]:
print(get)

[[ 5  4 10]
 [ 6  4  9]
 [ 6  5  2]]


In [ ]:
# in dimentional array
get.max(axis = 0)

# in same way we can find max also

array([ 6,  5, 10], dtype=int8)

In [ ]:
get.min(axis=1)

array([4, 4, 2], dtype=int8)

In [ ]:
get.max(axis = 1)

array([10,  9,  6], dtype=int8)

In [ ]:
get.min(axis = 0)

array([5, 4, 2], dtype=int8)

# FILTRATION

In [ ]:
num

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20], dtype=int16)

In [ ]:
num < 8

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False])

In [ ]:
#and for the values
num[num<8]

array([0, 2, 4, 6], dtype=int16)

In [ ]:
# same for greater than
num > 8

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [ ]:
num[num>8]

array([10, 12, 14, 16, 18, 20], dtype=int16)

# ADDITION OF TWO ARRAYS

In [ ]:
num + num

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40], dtype=int16)

In [ ]:
# we can also add more than two arrays

In [ ]:
import numpy as np

In [ ]:
# adding and subtraction two different arrays

my_list = [[1,4,60],
          [5,7,9],
          [8,7,6]
          ]
my_list1 = [[4,9,1],
          [7,2,4],
          [8,4,3]
          ]

In [ ]:
arr = np.array(my_list, dtype = np.int8)
arr1 = np.array(my_list1, dtype = np.int8)

In [ ]:
arr + arr1

array([[ 5, 13, 61],
       [12,  9, 13],
       [16, 11,  9]], dtype=int8)

In [ ]:
arr - arr1

array([[-3, -5, 59],
       [-2,  5,  5],
       [ 0,  3,  3]], dtype=int8)

In [ ]:
# its only applicable when the shape of both arrays are same 

In [ ]:
import random

In [ ]:
number_array = np.array([random.choices(range(1000),k = 50)])
print(number_array)

[[895 600 485 531 810 776  90 485 417 210 788 751 907 320 700 313 884 100
   51 586  26 257 594 746 714 136 160 515 752 590 182 302 554 428 835 784
  903 981 719 612 837 136 667 969 487 912 579  62 767 574]]


In [ ]:
%timeit sorted(number_array[0])

6.55 µs ± 74.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# sorting of the array

In [ ]:
# arranging of the array is called sorting of an array
number_array_sorted = np.sort(number_array)

In [ ]:
number_array_sorted

array([[ 26,  51,  62,  90, 100, 136, 136, 160, 182, 210, 257, 302, 313,
        320, 417, 428, 485, 485, 487, 515, 531, 554, 574, 579, 586, 590,
        594, 600, 612, 667, 700, 714, 719, 746, 751, 752, 767, 776, 784,
        788, 810, 835, 837, 884, 895, 903, 907, 912, 969, 981]])

# sorting by not changing the name of the array

In [ ]:
number_array = np.array([random.choices(range(1000),k = 50)])
print(number_array)

[[922  74 451 145 802 359 161 439  34 740 330 663 903 517 297 818 831 592
  991 274 301 925  91 791 160 820 392 102 529 477 697 342  46 685 297 356
  861  84 708 945  24 565  99 723  16 936 170 297 597 783]]


In [ ]:
# here we r using a function sort for sorting it
number_array.sort()
print(number_array)

[[ 16  24  34  46  74  84  91  99 102 145 160 161 170 274 297 297 297 301
  330 342 356 359 392 439 451 477 517 529 565 592 597 663 685 697 708 723
  740 783 791 802 818 820 831 861 903 922 925 936 945 991]]


# sorting of an array by specifing the column or a specific row

In [ ]:
get

array([[ 5,  4, 10],
       [ 6,  4,  9],
       [ 6,  5,  2]], dtype=int8)

along horizontal axis or row wise

In [ ]:
np.sort(get, axis = 0)

array([[ 5,  4,  2],
       [ 6,  4,  9],
       [ 6,  5, 10]], dtype=int8)

along vertical axis or column wise

In [ ]:
np.sort(get, axis = 1)

array([[ 4,  5, 10],
       [ 4,  6,  9],
       [ 2,  5,  6]], dtype=int8)

along with both 

In [ ]:
print(get)

[[ 5  4 10]
 [ 6  4  9]
 [ 6  5  2]]


In [ ]:
#this only sorts the array collum wise
np.sort(get)  

array([[ 4,  5, 10],
       [ 4,  6,  9],
       [ 2,  5,  6]], dtype=int8)

In [ ]:
np.sort(np.sort(get,axis = 0),axis = 1)

array([[ 2,  4,  5],
       [ 4,  6,  9],
       [ 5,  6, 10]], dtype=int8)